---
title: "Module 3 v2"
format: html
editor: visual
---

```{r}
#| echo: false
#| warning: false
#| message: false
#| error: false


library(tidyverse)
library(knitr)
library(psych)
library(car)
library(kableExtra)
library(MASS)

# Load the data from google sheets
df <- read_csv("Mod3Data.csv")
kable(round(head(df),2))
```

# Data Preparation

```{r}
#| echo: false
#| warning: false
#| message: false
#| error: false

# calculate sum scores for x1 to x7 after conducting a Cronbach's alpha analysis
xCA <- alpha(df[,5:11], check.keys = TRUE)
xCA

summary(xCA)

# create a new variable for the sum of x1 to x7
df$sumX <- rowSums(df[,5:11])

# show bivariate plots of x1 to x7
pairs.panels(df[,5:11])

# make all the f variables factors
df$f1.f <- as.factor(df$f1)
df$f2.f <- as.factor(df$f2)
df$f3.f <- as.factor(df$f3)
df$f4.f <- as.factor(df$f4)
df$f5.f <- as.factor(df$f5)
df$f6.f <- as.factor(df$f6)
df$f7.f <- as.factor(df$f7)
df$f8.f <- as.factor(df$f8)


```

```{r}
#| echo: false
#| warning: false
#| message: false
#| error: false

# calculate sum scores for x1 to x7 after conducting a Cronbach's alpha analysis
xCAdrop <- alpha(df[,c(5,6,7,10,11)], check.keys = TRUE)
xCAdrop

summary(xCAdrop)

# create a new variable for the x subset
df$sumXdrop <- rowSums(df[,c(5,6,7,10,11)])

# show bivariate plots of x1 to x7
pairs.panels(df[,c(5,6,7,10,11)])
```

# Data Analysis

## Bivariate Analysis (Noise!)

```{r}
#| echo: false
#| warning: false
#| message: false
#| error: false

# Bivariate model

mod <- lm(y2 ~ sumXdrop, data = df)
summary(mod)
```

```{r}
#| echo: false
#| warning: false
#| message: false
#| error: false

# plot the data
ggplot(df, aes(x = sumXdrop, y = y2)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(title = "Bivariate Analysis", x = "Sum of X Subset", y = "Y2")

```

## Multivariate Analysis (Nothing upon Nothing)

```{r}
#| echo: false
#| warning: false
#| message: false
#| error: false

# Multivariate model

mod2 <- lm(y2 ~ x1 + x2 + x3 + x6 + x7, data = df)
summary(mod2)


kable(vif(mod2), col.names = c("Variable", "VIF"))

mod3 <- lm(y2 ~ sumXdrop + f2, data = df)
summary(mod3)

kable(vif(mod3), col.names = c("Variable", "VIF"))


```

```{r}
#| echo: false
#| warning: false
#| message: false
#| error: false

# plot the results of

ggplot(df, aes(x = sumXdrop, y = y2, color = f2.f)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(title = "Multivariate Analysis", x = "Sum of X Subset", y = "Y2")

```

# Fitting our Model (Better) (But Also Not Really Cause Log Didn't Do Anything)

```{r}
#| echo: false
#| warning: false
#| message: false
#| error: false

df$log_sumXdrop <- log(df$sumXdrop + 1)
mod_log <- lm(y2 ~ log_sumXdrop + f2, data = df)
summary(mod_log)

```

```{r}
#| echo: false
#| warning: false
#| message: false
#| error: false

# plot the results of the log transform

ggplot(df, aes(x = log_sumXdrop, y = y2)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", formula = y ~ x, se = TRUE, color = "blue") +
  labs(
    title = "Scatterplot with Regression Line",
    x = "Log-transformed Sum of X Subset (log_sumXdrop)",
    y = "y2"
  )

```
